#pragma once

#include "NativeGameplayTags.h"

namespace ColorboundGameplayTags 
{
	COLORBOUND_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatusTag_Hit);
	COLORBOUND_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatusTag_Knockback);

	COLORBOUND_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ComboWindowOpen);
	COLORBOUND_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ComboWindowClosed);

	COLORBOUND_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);

	COLORBOUND_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTag_HitReact);
	COLORBOUND_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTag_Knockback);


}